title: Disinfo Day 2024 @UT Austin
description: Disinfo Day 2024 @UT Austin
  ---
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']
ga_id: UA-144588579-1
